apiVersion: v1
kind: Namespace
metadata:
  name: demo-ops
---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo-ops-quota
  namespace: demo-ops
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ops-deployment
  namespace: demo-ops
spec:
  selector:
    matchLabels:
      app: demo-ops
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-ops
    spec:
      containers:

      - name: redis
        image: redis:latest
        resources:
         limits:
          memory: "400Mi"
          cpu: "400m"
         requests:
          memory: "200Mi"
          cpu: "200m"
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: datadir

      - name: app
        image: gyan2930/demo-image
        resources:
         limits:
          memory: "400Mi"
          cpu: "400m"
         requests:
          memory: "200Mi"
          cpu: "200m"
        env:
        - name: DEMO_APP_ADDR
          value: localhost:8000 
        - name: DEMO_REDIS_ADDR
          value: localhost:6379
        ports:
        - containerPort: 8000
      volumes:
      - name: datadir
        hostPath:
         path: /data
         type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: demo-ops
  namespace: demo-ops
spec:
  type: NodePort
  selector:
    app: demo-ops
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
