version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - /data:/data
    networks:
      - app-network
    ports:
      - "6379:6379"

  demo:
    depends_on:
      - redis
    build: 
     context: .
     dockerfile: demo-app-dockerfile
    image: demo-app
    container_name: demo
    restart: unless-stopped
    environment:
      - DEMO_APP_ADDR=demo:8000
      - DEMO_REDIS_ADDR=redis:6379
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
